---
title: "Participant data for Big Data Big Impact"
author: "Tony Hui"
date: "March 2, 2016"
output: 
  html_document: 
    keep_md: yes
---

Competition information: http://makedatasense.ca/data-science-competition/#econdata

```{r, include=FALSE}
require(dplyr)
require(ggplot2)
require(data.table)
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
dat <- read.csv("participant_data.csv", stringsAsFactors = F) %>% tbl_df() %>%
  select(6:10) %>%
  setnames(c("year", "team", "dat_science", "economics", "faculty")) %>% 
  filter(dat_science != "") %>%
  mutate(team = grepl("Yes", team),
         dat_science = gsub(" \\(.*", "", dat_science),
         economics = gsub(" \\(.*", "", economics)) 

skill_order <- c("None", "Beginner", "Expert")

dat <- dat %>%
  mutate(dat_science = factor(dat_science, levels = skill_order),
         economics = factor(economics, levels = skill_order))
```

## How many people need teams?

```{r}
dat %>%
  group_by(team, faculty) %>%
  tally() %>%
  filter(team) %>%
  ggplot(aes(faculty, n)) +
  geom_bar(stat = "identity") +
  geom_text(aes(y = n+3, label = n))
```

## What skill level is everybody?

```{r}
dat %>%
  group_by(dat_science, economics) %>%
  tally() %>%
  ggplot(aes(dat_science, economics, fill = n)) +
  geom_bin2d()+
  geom_text(aes(label = n)) +
  scale_fill_gradient(low = "white", high = "red4")
```

## What skill level are people who are looking for teams

```{r}
dat %>%
  filter(team) %>%
  group_by(dat_science, economics) %>%
  tally() %>%
  ggplot(aes(dat_science, economics, fill = n)) +
  geom_bin2d()+
  geom_text(aes(label = n)) +
  scale_fill_gradient(low = "white", high = "red4")
```

## What skill level is people not looking for teams

```{r}
dat %>%
  filter(!team) %>%
  group_by(dat_science, economics) %>%
  tally() %>%
  ggplot(aes(dat_science, economics, fill = n)) +
  geom_bin2d()+
  geom_text(aes(label = n)) +
  scale_fill_gradient(low = "white", high = "red4")
```

## What faculty are people coming from?

```{r}
dat %>%
  ggplot(aes(faculty)) +
  geom_bar() 
```

## What year is everybody in?

```{r}
dat %>%
  ggplot(aes(year)) +
  geom_bar() 
```

## Which faculty has highest percentage of experts?

```{r}
dat %>%
  mutate(expert = grepl("Expert", dat_science) | grepl("Expert", economics)) %>%
  group_by(faculty, expert) %>%
  tally() %>%
  mutate(sum = sum(n)) %>%
  filter(expert) %>%
  ggplot(aes(faculty, n/sum)) +
  geom_bar(stat = "identity") +
  ylab("Percent of experts")
```

## Experts by year

```{r}
dat %>%
  mutate(expert = grepl("Expert", dat_science) | grepl("Expert", economics)) %>%
  group_by(year, expert) %>%
  tally() %>%
  mutate(sum = sum(n)) %>%
  filter(expert) %>%
  ggplot(aes(year, n/sum)) +
  geom_bar(stat = "identity") +
  ylab("Percent of experts")
```

